### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by KarmaMod** [Perfare/Riru-Il2CppDumper#76]
Game crashes as soon as it tries to dump. I tried auto-il2cppdumper as well and getting same crash as well, the crash is caused by the dumper, not the game.

Game link: https://apkcombo.com/apk-downloader/?package=com.square_enix.android_googleplay.dqdaihb&device=default&arches=arm64-v8a&sdkInt=default&format=apk&dpi=480&lang=en

```
2021-10-19 16:26:25.713 14853-14864/? I/Perfare: UnityVersion: 2020.2.4f1
2021-10-19 16:26:25.713 14853-14864/? I/Perfare: VersionAbove2018dot3: on
2021-10-19 16:26:25.713 14853-14864/? I/Perfare: il2cpp_handle: 0x82f5f73a131abaf9
2021-10-19 16:26:25.727 14853-14864/? I/Perfare: typeDefinitionsCount: 22914
2021-10-19 16:26:25.734 14853-14864/? I/Perfare: il2cpp_base: 6cd5700000
2021-10-19 16:26:25.739 14853-14864/? E/CRASH: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2021-10-19 16:26:25.739 14853-14864/? E/CRASH: Version '2020.3.10f1 (297d780c91bc)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
2021-10-19 16:26:25.739 14853-14864/? E/CRASH: Build fingerprint: 'xxx'
2021-10-19 16:26:25.739 14853-14864/? E/CRASH: Revision: 'pvt'
2021-10-19 16:26:25.739 14853-14864/? E/CRASH: ABI: 'arm64'
2021-10-19 16:26:25.739 14853-14864/? E/CRASH: Timestamp: 2021-10-19 16:26:25+0200
2021-10-19 16:26:25.739 14853-14864/? E/CRASH: pid: 14853, tid: 14864, name: gleplay.dqdaih  >>> com.square_enix.android_googleplay.dqdaihb <<<
2021-10-19 16:26:25.739 14853-14864/? E/CRASH: uid: 10312
2021-10-19 16:26:25.739 14853-14864/? E/CRASH: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x66c568ee60
2021-10-19 16:26:25.739 14853-14864/? E/CRASH:     x0  b4000066c568ee60  x1  ffffffffbad53dec  x2  b400006e1055d110  x3  0000006d3c65774c
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:     x4  0000006e1055d240  x5  0000000000000004  x6  ff2f2f2f2f2f3634  x7  7f7f7f7f7f7f7f7f
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:     x8  b4000066c568ee60  x9  fffffff983fdce20  x10 0000000000000018  x11 0000000000000014
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:     x12 0000000000000009  x13 0000000000000018  x14 0000006d3c657378  x15 0000000000000000
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:     x16 0000006fe2351b70  x17 0000006fe22e3380  x18 0000006cf1e28000  x19 0000006d3c657cc0
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:     x20 0000006fe2348ca8  x21 0000006d3c657cc0  x22 0000000000003a05  x23 0000000000003a05
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:     x24 0000006d3c657cc0  x25 0000006d3c657cc0  x26 0000006d3c657ff8  x27 00000000000fc000
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:     x28 0000006d3c55f000  x29 0000006d3c657770
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:     sp  0000006d3c657760  lr  0000006d4884cb1c  pc  0000006d4884cb1c
2021-10-19 16:26:25.740 14853-14864/? E/CRASH: backtrace:
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:       #00 pc 000000000005bb1c  <anonymous:0000006d487f1000>
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:       #01 pc 000000000005c140  <anonymous:0000006d487f1000>
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:       #02 pc 000000000005a1a4  <anonymous:0000006d487f1000>
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:       #03 pc 0000000000059de8  <anonymous:0000006d487f1000>
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:       #04 pc 00000000000551a0  <anonymous:0000006d487f1000>
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:       #05 pc 00000000000afce8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 41c660c694a41af9265f00d2b0edc316)
2021-10-19 16:26:25.740 14853-14864/? E/CRASH:       #06 pc 00000000000502c8  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 41c660c694a41af9265f00d2b0edc316)
2021-10-19 16:26:25.860 1158-2506/? D/slpi: vcnl36866_ALS_handle:lux:53.251663, last_ps:near[524], als_raw:171, ir_raw:33, als_scale:1.497179, THDH:84,THDL:56,CONF:962, PSTH  L 280 H 4095 INT 0x4ff
2021-10-19 16:26:25.896 1158-2506/? D/slpi: vcnl36866_PS_handle: ps: far[226] , last_lux:52.751663,  PS_THDH:4095, PS_THDL:280,PS_CONF1:39224,PS_CONF3:33288,PS_CANC:0,PS_AC:0, PS_INT:0x1ff
2021-10-19 16:26:25.897 1158-2506/? D/slpi: vcnl36866_proximity_mot_update_pth: ps: FAR[226], last_lux:52.751663, PS_THDH:360, PS_THDL:40, PS_CONF1:39224, PS_CONF3:33288, PS_CANC:0, PS_AC:0, PS_INT:0x1ff
2021-10-19 16:26:25.907 1158-2506/? D/slpi: vcnl36866_ALS_handle:lux:104.634850, last_ps:far[243], als_raw:336, ir_raw:48, als_scale:1.497179, THDH:205,THDL:137,CONF:962, PSTH  L 40 H 360 INT 0x4ff
2021-10-19 16:26:25.939 14853-14891/? E/CRASH: other thread is trapped; signum = 11
2021-10-19 16:26:25.940 14853-14891/? E/AndroidRuntime: FATAL EXCEPTION: UnityMain
    Process: com.square_enix.android_googleplay.dqdaihb, PID: 14853
    java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Version '2020.3.10f1 (297d780c91bc)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
    Build fingerprint: 'xxx'
    Revision: 'pvt'
    ABI: 'arm64'
    Timestamp: 2021-10-19 16:26:25+0200
    pid: 14853, tid: 14864, name: gleplay.dqdaih  >>> com.square_enix.android_googleplay.dqdaihb <<<
    uid: 10312
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x66c568ee60
        x0  b4000066c568ee60  x1  ffffffffbad53dec  x2  b400006e1055d110  x3  0000006d3c65774c
        x4  0000006e1055d240  x5  0000000000000004  x6  ff2f2f2f2f2f3634  x7  7f7f7f7f7f7f7f7f
        x8  b4000066c568ee60  x9  fffffff983fdce20  x10 0000000000000018  x11 0000000000000014
        x12 0000000000000009  x13 0000000000000018  x14 0000006d3c657378  x15 0000000000000000
        x16 0000006fe2351b70  x17 0000006fe22e3380  x18 0000006cf1e28000  x19 0000006d3c657cc0
        x20 0000006fe2348ca8  x21 0000006d3c657cc0  x22 0000000000003a05  x23 0000000000003a05
        x24 0000006d3c657cc0  x25 0000006d3c657cc0  x26 0000006d3c657ff8  x27 00000000000fc000
        x28 0000006d3c55f000  x29 0000006d3c657770
        sp  0000006d3c657760  lr  0000006d4884cb1c  pc  0000006d4884cb1c
    
    backtrace:
          #00 pc 000000000005bb1c  <anonymous:0000006d487f1000>
          #01 pc 000000000005c140  <anonymous:0000006d487f1000>
          #02 pc 000000000005a1a4  <anonymous:0000006d487f1000>
          #03 pc 0000000000059de8  <anonymous:0000006d487f1000>
          #04 pc 00000000000551a0  <anonymous:0000006d487f1000>
          #05 pc 00000000000afce8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 41c660c694a41af9265f00d2b0edc316)
          #06 pc 00000000000502c8  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 41c660c694a41af9265f00d2b0edc316)
    
        at Unknown.0x6d4884cb1c(Unknown Source:0)
        at Unknown.0x6d4884d140(Unknown Source:0)
        at Unknown.0x6d4884b1a4(Unknown Source:0)
        at Unknown.0x6d4884ade8(Unknown Source:0)
        at Unknown.0x6d488461a0(Unknown Source:0)
        at libc.__pthread_start(void*)(__pthread_start:64)
        at libc.__start_thread(__start_thread:64)
```

**Comment by Perfare** [comment]
fixed.
