### ISSUE TITLE
dump

### ISSUE THREAD

**Issue by ndl1302732** [Perfare/Riru-Il2CppDumper#9]
测试机器: Pixel XL (代号marlin)
系统Android8.1 （google/marlin/marlin:8.1.0/OPM1.171019.011/4448085:user/release-keys）
Native Hook框架   ele7inlinehook （whale会崩溃）

测试app和编译好的模块等
    链接：https://pan.baidu.com/s/1J-V1XDn-HRf43ndRJB_nJw 
    提取码：4kdt

问题代码:

while (!il2cpp_handle) {
        sleep(1);
    }
    sleep(5);
    LOGI("before il2cpp_dump");
    il2cpp_dump(il2cpp_handle, game_data_dir); ---> 这里会崩溃
    LOGI("after il2cpp_dump");

hook代码如下:

typedef void* (* PFN___android_dlopen_ext) (const char* filename,int flags,const void* caller_addr);
PFN___android_dlopen_ext pfn_AndroidDlopenExt = NULL;
void* __android_dlopen_ext_new(const char* filename,int flags,const void* caller_addr){
    //LOGI("__android_dlopen_ext %s", filename);
    void *handle = pfn_AndroidDlopenExt(filename, flags, caller_addr);
    dlopen_process(filename, handle);
    return handle;

}
......................................................................................

    if (api_level > 25) {
        void *libdl_handle = dlopen("libdl.so", RTLD_LAZY);
        void *__loader_dlopen_addr = dlsym(libdl_handle, "__loader_dlopen");
        LOGI("__loader_dlopen at: %p", __loader_dlopen_addr);
        hook("__loader_dlopen", __loader_dlopen_addr, (void *) __android_dlopen_ext_new,
                            (void **) &pfn_AndroidDlopenExt);

-----------------------------------------------------------------------------------------
LOG日志如下:
2020-08-11 13:53:29.482 2487-2498/? I/Perfare: before il2cpp_dump
2020-08-11 13:53:29.482 2487-2498/? I/Perfare: il2cpp_handle: 0x8a8b4883
2020-08-11 13:53:29.484 2487-2498/? I/Perfare: typeDefinitionsCount: 2227
2020-08-11 13:53:29.487 2487-2498/? I/Perfare: il2cpp_base: c8311000
2020-08-11 13:53:29.487 2487-2498/? I/Perfare: Assembly::Load: 0xc86b62e8
2020-08-11 13:53:29.487 2487-2498/? I/Perfare: Assembly::GetTypes: 0xc86b60b8
2020-08-11 13:53:29.487 2487-2498/? I/Perfare: dumping...

崩溃堆栈信息:
2020-08-11 13:56:08.468 1902-1909/? E/ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
2020-08-11 13:56:08.468 1902-1909/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
2020-08-11 13:56:08.806 680-1001/? E/volume_listener: check_and_set_gain_dep_cal: Failed to set gain dep cal level
2020-08-11 13:56:08.809 1902-1909/? E/ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
2020-08-11 13:56:08.809 1902-1909/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
2020-08-11 13:56:14.099 2210-2253/? E/ReloadingLock: Finalizing LOCKED Token[canvas 2020-08-11 13:53:30.233]
2020-08-11 13:56:14.546 4318-4325/? E/CRASH: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
2020-08-11 13:56:14.546 4318-4325/? E/CRASH: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-08-11 13:56:14.546 4318-4325/? E/CRASH: Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a'
2020-08-11 13:56:14.546 4318-4325/? E/CRASH: Build fingerprint: 'google/marlin/marlin:8.1.0/OPM1.171019.011/4448085:user/release-keys'
2020-08-11 13:56:14.546 4318-4325/? E/CRASH: Revision: '0'
2020-08-11 13:56:14.546 4318-4325/? E/CRASH: pid: 4318, tid: 4325, name: og.test.LogTes  >>> com.com.log.test.LogTest <<<
2020-08-11 13:56:14.546 4318-4325/? E/CRASH:     r0 00638758  r1 cbb12b48  r2 00000000  r3 80000000
2020-08-11 13:56:14.546 4318-4325/? E/CRASH:     r4 e48a8fbc  r5 e48a8fa0  r6 00000000  r7 ca630360
2020-08-11 13:56:14.546 4318-4325/? E/CRASH:     r8 c438e710  r9 c438e844  sl c81427ca  fp cbb126f0
2020-08-11 13:56:14.546 4318-4325/? E/CRASH:     ip c8b10338  sp cbb126d8  lr c84daed4  pc c84dae30  cpsr c3ee6a00
2020-08-11 13:56:14.546 4318-4325/? E/CRASH: backtrace:
2020-08-11 13:56:14.652 4318-4325/? E/CRASH: 	#00  pc 00148e30  /data/app/com.com.log.test.LogTest-LDhSYfGSCxbCD25ttfX_gQ==/lib/arm/libil2cpp.so
2020-08-11 13:56:14.652 4318-4325/? E/CRASH: 	#01  pc 001477d0  /data/app/com.com.log.test.LogTest-LDhSYfGSCxbCD25ttfX_gQ==/lib/arm/libil2cpp.so
2020-08-11 13:56:14.652 4318-4325/? E/CRASH: 	#02  pc 00214fc0  /data/app/com.com.log.test.LogTest-LDhSYfGSCxbCD25ttfX_gQ==/lib/arm/libil2cpp.so
2020-08-11 13:56:14.652 4318-4325/? E/CRASH: 	#03  pc 00214ef0  /data/app/com.com.log.test.LogTest-LDhSYfGSCxbCD25ttfX_gQ==/lib/arm/libil2cpp.so
2020-08-11 13:56:14.652 4318-4325/? E/CRASH: 	#04  pc 0000bafb  /system/lib/libriru_il2cppdumper.so
2020-08-11 13:56:14.652 4318-4325/? E/CRASH: memory near r0:
2020-08-11 13:56:14.652 4318-4325/? E/CRASH:     00638738 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.652 4318-4325/? E/CRASH:     00638748 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.652 4318-4325/? E/CRASH:     00638758 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.652 4318-4325/? E/CRASH:     00638768 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.653 4318-4325/? E/CRASH:     00638778 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.653 4318-4325/? E/CRASH:     00638788 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.653 4318-4325/? E/CRASH:     00638798 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.653 4318-4325/? E/CRASH:     006387a8 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.653 4318-4325/? E/CRASH:     006387b8 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.653 4318-4325/? E/CRASH:     006387c8 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.653 4318-4325/? E/CRASH:     006387d8 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.653 4318-4325/? E/CRASH:     006387e8 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.653 4318-4325/? E/CRASH:     006387f8 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.653 4318-4325/? E/CRASH:     00638808 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.653 4318-4325/? E/CRASH:     00638818 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.653 4318-4325/? E/CRASH:     00638828 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.653 4318-4325/? E/CRASH: memory near r3:
2020-08-11 13:56:14.653 4318-4325/? E/CRASH:     7fffffe0 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     7ffffff0 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     80000000 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     80000010 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     80000020 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     80000030 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     80000040 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     80000050 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     80000060 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     80000070 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     80000080 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     80000090 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     800000a0 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     800000b0 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     800000c0 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH:     800000d0 ffffffff ffffffff ffffffff ffffffff  ................
2020-08-11 13:56:14.654 4318-4325/? E/CRASH: code around pc:
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84dae10 e1a07002 e1a04005 e5b4001c e3500000  .p...@........P.
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84dae20 18bd8bf0 eb000024 e1a06000 e59f0084  ....$....`......
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84dae30 e8960300 e3a01001 e08f0000 e3a02000  ............. ..
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84dae40 e5900028 eb00abf1 e0491008 e3570000  (.........I...W.
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84dae50 e1a08141 0a000006 e3580000 1a000004  A.........X.....
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84dae60 e3a01001 ebffe44a e1a02000 e5827010  ....J.... ...p..
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84dae70 ea00000c e1a01008 ebffe445 e1a02000  ........E.... ..
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84dae80 e8960003 e1500001 0a000006 e0821108  ......P.........
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84dae90 e281100c e4903004 e4013004 e5963004  .....0...0...0..
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84daea0 e1500003 1afffffa e1a00005 e1a01004  ..P.............
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84daeb0 e8bd4bf0 eafd78f0 00638758 e92d4c10  .K...x..X.c..L-.
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84daec0 e28db008 e59f0038 e79f0000 e5900000  ....8...........
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84daed0 ebfd7985 e1a04000 e3540000 0a000006  .y...@....T.....
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84daee0 e59f0020 e3a02000 e5941000 e08f0000   .... ..........
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84daef0 e5841004 e1a01004 ebff84d8 e1a00004  ................
2020-08-11 13:56:14.655 4318-4325/? E/CRASH:     c84daf00 e8bd8c10 00638c88 00019e88 e92d4c10  ......c......L-.
2020-08-11 13:56:14.655 4318-4325/? E/CRASH: code around lr:
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daeb4 eafd78f0 00638758 e92d4c10 e28db008  .x..X.c..L-.....
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daec4 e59f0038 e79f0000 e5900000 ebfd7985  8............y..
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daed4 e1a04000 e3540000 0a000006 e59f0020  .@....T..... ...
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daee4 e3a02000 e5941000 e08f0000 e5841004  . ..............
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daef4 e1a01004 ebff84d8 e1a00004 e8bd8c10  ................
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daf04 00638c88 00019e88 e92d4c10 e28db008  ..c......L-.....
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daf14 e24dd008 e1a04000 e59f0038 e59f2038  ..M..@..8...8 ..
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daf24 e3a03000 e59f1034 e79f0000 e08f2002  .0..4........ ..
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daf34 e08f1001 e58d3004 e58d3000 e1a0300d  .....0...0...0..
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daf44 eb0002cb e1a01004 e3a02000 ebfffa1b  ......... ......
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daf54 e24bd008 e8bd8c10 00638664 004b83ee  ..K.....d.c...K.
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daf64 004b8362 e92d4c10 e28db008 e1a04000  b.K..L-......@..
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daf74 e59f0028 e59f1028 e3a03000 e59f2024  (...(....0..$ ..
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daf84 e79f0000 e08f1001 e08f2002 eb0002f5  ......... ......
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84daf94 e1a01004 e3a02000 e8bd4c10 eafffa07  ..... ...L......
2020-08-11 13:56:14.656 4318-4325/? E/CRASH:     c84dafa4 0063860c 004b830e 004b83e6 e92d4c10  ..c...K...K..L-.
2020-08-11 13:56:14.669 4318-4336/? E/CRASH: other thread is trapped; signum = 11
    
    --------- beginning of crash
2020-08-11 13:56:14.670 4318-4336/? E/AndroidRuntime: FATAL EXCEPTION: UnityMain
    Process: com.com.log.test.LogTest, PID: 4318
    java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
    Build fingerprint: 'google/marlin/marlin:8.1.0/OPM1.171019.011/4448085:user/release-keys'
    Revision: '0'
    pid: 4318, tid: 4325, name: og.test.LogTes  >>> com.com.log.test.LogTest <<<
        r0 00638758  r1 cbb12b48  r2 00000000  r3 80000000
        r4 e48a8fbc  r5 e48a8fa0  r6 00000000  r7 ca630360
        r8 c438e710  r9 c438e844  sl c81427ca  fp cbb126f0
        ip c8b10338  sp cbb126d8  lr c84daed4  pc c84dae30  cpsr c3ee6a00
    
        at libil2cpp.00148e30(Native Method)
        at libil2cpp.001477d0(Native Method)
        at libil2cpp.00214fc0(Native Method)
        at libil2cpp.00214ef0(Native Method)
        at libriru_il2cppdumper.0000bafb(Native Method)
2020-08-11 13:56:15.376 2210-2280/? E/EntrySyncManager: Cannot determine account name: drop request
2020-08-11 13:56:15.377 2210-2280/? E/NowController: Failed to access data from EntryProvider. ExecutionException.
    java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not complete scheduled request to refresh entries. ClientErrorCode: 3
        at com.google.common.util.concurrent.d.da(SourceFile:85)
        at com.google.common.util.concurrent.d.get(SourceFile:23)
        at com.google.common.util.concurrent.l.get(SourceFile:2)
        at com.google.android.apps.gsa.staticplugins.nowstream.b.a.af.aGC(SourceFile:21)
        at com.google.android.apps.gsa.staticplugins.nowstream.b.a.af.doInBackground(SourceFile:153)
        at com.google.android.apps.gsa.shared.util.concurrent.d.call(SourceFile:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.android.apps.gsa.shared.util.concurrent.a.ag.run(Unknown Source:4)
        at com.google.android.apps.gsa.shared.util.concurrent.a.bo.run(SourceFile:4)
        at com.google.android.apps.gsa.shared.util.concurrent.a.bo.run(SourceFile:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.google.android.apps.gsa.shared.util.concurrent.a.ak.run(SourceFile:6)
     Caused by: java.lang.RuntimeException: Could not complete scheduled request to refresh entries. ClientErrorCode: 3
        at com.google.android.apps.gsa.sidekick.main.i.u.ak(SourceFile:6)
        at com.google.common.util.concurrent.q.P(SourceFile:7)
        at com.google.common.util.concurrent.p.run(SourceFile:37)
        at com.google.common.util.concurrent.br.execute(SourceFile:3)
        at com.google.common.util.concurrent.d.a(SourceFile:264)
        at com.google.common.util.concurrent.d.addListener(SourceFile:134)
        at com.google.common.util.concurrent.p.b(SourceFile:3)
        at com.google.common.util.concurrent.ax.a(SourceFile:18)
        at com.google.android.apps.gsa.shared.util.concurrent.h.a(SourceFile:10)
        at com.google.android.apps.gsa.shared.util.concurrent.h.a(SourceFile:7)
        at com.google.android.apps.gsa.sidekick.main.i.r.a(SourceFile:15)
        at com.google.android.apps.gsa.sidekick.main.i.s.ak(SourceFile:8)
        at com.google.common.util.concurrent.q.P(SourceFile:7)
        at com.google.common.util.concurrent.p.run(SourceFile:37)
        at com.google.common.util.concurrent.br.execute(SourceFile:3)
        at com.google.common.util.concurrent.d.a(SourceFile:264)
        at com.google.common.util.concurrent.d.addListener(SourceFile:134)
        at com.google.common.util.concurrent.p.b(SourceFile:3)
        at com.google.common.util.concurrent.ax.a(SourceFile:18)
        at com.google.android.apps.gsa.shared.util.concurrent.h.a(SourceFile:10)
        at com.google.android.apps.gsa.shared.util.concurrent.h.a(SourceFile:7)
        at com.google.android.apps.gsa.sidekick.main.i.r.a(SourceFile:10)
        at com.google.android.apps.gsa.staticplugins.nowstream.b.a.af.aGC(SourceFile:20)
        at com.google.android.apps.gsa.staticplugins.nowstream.b.a.af.doInBackground(SourceFile:153) 
        at com.google.android.apps.gsa.shared.util.concurrent.d.call(SourceFile:2) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at com.google.android.apps.gsa.shared.util.concurrent.a.ag.run(Unknown Source:4) 
        at com.google.android.apps.gsa.shared.util.concurrent.a.bo.run(SourceFile:4) 
        at com.google.android.apps.gsa.shared.util.concurrent.a.bo.run(SourceFile:4) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
        at com.google.android.apps.gsa.shared.util.concurrent.a.ak.run(SourceFile:6) 
2020-08-11 13:56:15.520 1831-1966/? E/ModuleIdSetter: exception when setting module id
    java.lang.IllegalStateException: Unable to get current module info in ModuleManager created with non-module Context
        at com.google.android.chimera.config.ModuleManager.getCurrentModule(:com.google.android.gms@202614019@20.26.14 (040400-320008519):2)
        at aeqs.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):4)
        at aeqv.b(:com.google.android.gms@202614019@20.26.14 (040400-320008519):9)
        at aend.a(Unknown Source:0)
        at rlj.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):0)
        at rhs.c(:com.google.android.gms@202614019@20.26.14 (040400-320008519):1)
        at rhq.b(:com.google.android.gms@202614019@20.26.14 (040400-320008519):1)
        at rkh.b(:com.google.android.gms@202614019@20.26.14 (040400-320008519):6)
        at rkh.c(:com.google.android.gms@202614019@20.26.14 (040400-320008519):6)
        at rkh.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):63)
        at rkl.handleMessage(:com.google.android.gms@202614019@20.26.14 (040400-320008519):72)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at aefh.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):2)
        at aefh.dispatchMessage(:com.google.android.gms@202614019@20.26.14 (040400-320008519):12)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2020-08-11 13:56:15.689 1831-1966/? E/ModuleIdSetter: exception when setting module id
    java.lang.IllegalStateException: Unable to get current module info in ModuleManager created with non-module Context
        at com.google.android.chimera.config.ModuleManager.getCurrentModule(:com.google.android.gms@202614019@20.26.14 (040400-320008519):2)
        at aeqs.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):4)
        at aeqv.b(:com.google.android.gms@202614019@20.26.14 (040400-320008519):9)
        at aend.a(Unknown Source:0)
        at rlj.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):0)
        at rhs.c(:com.google.android.gms@202614019@20.26.14 (040400-320008519):1)
        at rhq.b(:com.google.android.gms@202614019@20.26.14 (040400-320008519):1)
        at rkh.b(:com.google.android.gms@202614019@20.26.14 (040400-320008519):6)
        at rkh.c(:com.google.android.gms@202614019@20.26.14 (040400-320008519):6)
        at rkh.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):63)
        at rkl.handleMessage(:com.google.android.gms@202614019@20.26.14 (040400-320008519):72)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at aefh.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):2)
        at aefh.dispatchMessage(:com.google.android.gms@202614019@20.26.14 (040400-320008519):12)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2020-08-11 13:56:15.716 1831-1966/? E/ModuleIdSetter: exception when setting module id
    java.lang.IllegalStateException: Unable to get current module info in ModuleManager created with non-module Context
        at com.google.android.chimera.config.ModuleManager.getCurrentModule(:com.google.android.gms@202614019@20.26.14 (040400-320008519):2)
        at aeqs.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):4)
        at aeqv.b(:com.google.android.gms@202614019@20.26.14 (040400-320008519):9)
        at aend.a(Unknown Source:0)
        at rlj.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):0)
        at rhs.c(:com.google.android.gms@202614019@20.26.14 (040400-320008519):1)
        at rhq.b(:com.google.android.gms@202614019@20.26.14 (040400-320008519):1)
        at rkh.b(:com.google.android.gms@202614019@20.26.14 (040400-320008519):6)
        at rkh.c(:com.google.android.gms@202614019@20.26.14 (040400-320008519):6)
        at rkh.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):63)
        at rkl.handleMessage(:com.google.android.gms@202614019@20.26.14 (040400-320008519):72)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at aefh.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):2)
        at aefh.dispatchMessage(:com.google.android.gms@202614019@20.26.14 (040400-320008519):12)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2020-08-11 13:56:16.056 2683-2825/? E/bt_btm: BTM_BleObserve Observe Already Active
2020-08-11 13:56:16.083 1831-1966/? E/ModuleIdSetter: exception when setting module id
    java.lang.IllegalStateException: Unable to get current module info in ModuleManager created with non-module Context
        at com.google.android.chimera.config.ModuleManager.getCurrentModule(:com.google.android.gms@202614019@20.26.14 (040400-320008519):2)
        at aeqs.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):4)
        at aeqv.b(:com.google.android.gms@202614019@20.26.14 (040400-320008519):9)
        at aend.a(Unknown Source:0)
        at rlj.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):0)
        at rhs.c(:com.google.android.gms@202614019@20.26.14 (040400-320008519):1)
        at rhq.b(:com.google.android.gms@202614019@20.26.14 (040400-320008519):1)
        at rkh.b(:com.google.android.gms@202614019@20.26.14 (040400-320008519):6)
        at rkh.c(:com.google.android.gms@202614019@20.26.14 (040400-320008519):6)
        at rkh.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):63)
        at rkl.handleMessage(:com.google.android.gms@202614019@20.26.14 (040400-320008519):72)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at aefh.a(:com.google.android.gms@202614019@20.26.14 (040400-320008519):2)
        at aefh.dispatchMessage(:com.google.android.gms@202614019@20.26.14 (040400-320008519):12)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2020-08-11 13:56:26.733 497-523/? E/SurfaceFlinger: Permission Denial: can't openGlobalTransaction pid=4318, uid<=10128
2020-08-11 13:56:26.733 4318-4318/? E/BpSurfaceComposerClient: Failed to transact (-1)
2020-08-11 13:56:26.735 497-960/? E/SurfaceFlinger: Permission Denial: can't openGlobalTransaction pid=4318, uid<=10128
2020-08-11 13:56:26.735 4318-4318/? E/BpSurfaceComposerClient: Failed to transact (-1)
2020-08-11 13:56:26.901 680-1001/? E/volume_listener: check_and_set_gain_dep_cal: Failed to set gain dep cal level
2020-08-11 13:56:26.901 680-680/? E/volume_listener: check_and_set_gain_dep_cal: Failed to set gain dep cal level
2020-08-11 13:58:37.725 3468-3577/? E/PlayCommon: [59] aqxy.c(141): Failed to connect to server for server timestamp: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xd9eed5c0: I/O error during system call, Connection reset by peer
2020-08-11 13:58:37.778 3468-3577/? E/PlayCommon: [59] aqxy.c(182): Failed to connect to server for log upload.
2020-08-11 13:58:53.854 4118-4149/? E/PlayCommon: [73] PlayEventLogger.uploadLog: Failed to connect to server: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xdc8a56c0: I/O error during system call, Connection reset by peer
2020-08-11 14:04:04.026 4118-4149/? E/PlayCommon: [73] PlayEventLogger.uploadLog: Failed to connect to server: java.net.SocketTimeoutException: failed to connect to play.googleapis.com/216.58.200.234 (port 443) from /192.168.1.132 (port 43002) after 10000ms

**Comment by ndl1302732** [comment]
忘记开//#define VersionAboveV24 这个宏了。后面再试下
